apiVersion: v1
kind: Secret
metadata:
  name: ms-comp-user
type: Opaque
data:
  username: cG9zdGdyZXM=
  password: YWRtaW4=

---
apiVersion: v1
kind: Secret
metadata:
  name: ms-comp-course
type: Opaque
data:
  username: cm9vdA==
  password: YWRtaW4=