apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-persistence-volume-claim
spec:
  volumeName: mysql-persistence-volume
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 2Gi